version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.61.0
    container_name: jaeger
    ports:
      - "4317:4317"
      - "16686:16686"
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
